name: Publish

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: MineInAbyss/publish-action@v3
        with:
          maven-username: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}
          release-files: |
            ${{ github.workspace }}/publish/*.jar

# Temporarily disable because artifact isn't being uploaded correctly
#  deploy:
#    permissions:
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    if: ${{ github.ref == 'refs/heads/master' }}
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1
